version: 2

before:
  hooks:
    - go mod tidy

builds:
  - binary: kss
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      # - windows
      - darwin
    goarch:
      - amd64
      - arm64

archives:
  - formats: [tar.gz]
    # this name template makes the OS and Arch compatible with the results of `uname`.
    name_template: >-
      {{ .ProjectName }}_
      {{- .Os }}_
      {{- .Arch }}
    # use zip for windows archives
    format_overrides:
      - goos: windows
        formats: [zip]

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

release:
  github:
    owner: moonlight8978
    name: kubernetes-schema-store

  footer: >-

    ---

    Released by [GoReleaser](https://github.com/goreleaser/goreleaser).
